apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-manifests
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-app-examples/kustomize-manifests
    repoURL: http://gitlab-192-168-1-102.nip.io:30080/Morpheus/gitops-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
