apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: helloworld-kustomize-helm
spec:
    generators:
    - list:
        elements:
        - namespace: gitops-demo
          server: https://kubernetes.default.svc
    template:
        metadata:
            name: 'helloworld-kustomize-helm'
        spec:
            destination:
                namespace: '{{namespace}}'
                server: '{{server}}'
            project: default
            source:
                repoURL: http://gitlab-192-168-1-102.nip.io:30080/Morpheus/gitops-demo.git
                targetRevision: HEAD
                path: 'argo-app-examples/kustomize-helm-applicationset/helloworld'
                plugin:
                    name: kustomized-helm
                    env:
                    - name: HELM_ARGS
                      value: "--include-crds"
                    - name: HELM_VALUES
                      value: |
                        replicaCount: 2
            syncPolicy:
                automated:
                    prune: true
