apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld.fullname" . }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
  selector:
    {{- include "helloworld.selectorLabels" . | nindent 4 }}