apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: helloworld-kustomize
spec:
    generators:
    - list:
        elements:
        - namespace: gitops-demo
          server: https://kubernetes.default.svc
          values:
            image: morpheusph/hello:latest
    template:
        metadata:
            name: 'helloworld-kustomize'
        spec:
            destination:
                namespace: '{{namespace}}'
                server: '{{server}}'
            project: default
            source:
                repoURL: http://gitlab-192-168-1-102.nip.io:30080/Morpheus/gitops-demo.git
                targetRevision: HEAD
                path: 'argo-app-examples/kustomize-applicationset/helloworld'
                helm:
                  parameters:
                    - name: image
                      value: '{{values.image}}'                    
            syncPolicy:
                automated:
                    prune: true
